### PR TITLE
refactor: modularize system

### LINKED ISSUE #94: Switch backend from Node to Flask

### PR DESCRIPTION
**Pull request by peter-gy**
### Goals

- Split up the middleware and the frontend to fully isolated, self-contained modules
- Refactor the frontend, support communication with the middleware

closes #94

### CODE REVIEW

**Comment by peter-gy** [comment]
Hi @tla!

I marked this PR as a draft, because I would like to fully dockerize the repo before having it merged. That is, I would edit the top-level `docker-compose.yml` to account for the new service structure. However, for this, I need to get a better overview on how the system will be deployed.

Are we going to have the frontend and the middleware on two different hosts or should we use an nginx reverse proxy on a single host to expose the static web bundle under `https://<hostname>/` and the middleware under `https://<hostname>/middleware`? (or any possible path / domain based configuration)

Also, is there a live instance of the Stemmarest API deployed somewhere?

**Comment by peter-gy** [comment]
Post-meeting requirements:

- create a single `Dockerfile` to serve the middleware and the static site
- cleanup the docker-related files in the root, have a single `docker-compose.yml`
- update the workflows to push the stemmaweb image to the container registry

**Comment by tla** [comment]
> Are we going to have the frontend and the middleware on two different hosts or should we use an nginx reverse proxy on a single host to expose the static web bundle under `https://<hostname>/` and the middleware under `https://<hostname>/middleware`? (or any possible path / domain based configuration)

The second option would fit better into our architecture (I currently run it at https://stemmaweb.net/stemmaweb with a Wordpress instance on the root site. So the static bundle would be under `/stemmaweb` and the middleware under another endpoint (e.g. `/stemmaweb/request`). As discussed in the call, I think these should both go into the same container; I have a hard time seeing a use case for splitting the middleware into its own container.

> Also, is there a live instance of the Stemmarest API deployed somewhere?

Yes, it is running behind https://test.stemmaweb.net/stemmaweb . I'll give you the access details separately.

**Comment by peter-gy** [comment]
> > Are we going to have the frontend and the middleware on two different hosts or should we use an nginx reverse proxy on a single host to expose the static web bundle under `https://<hostname>/` and the middleware under `https://<hostname>/middleware`? (or any possible path / domain based configuration)
> 
> The second option would fit better into our architecture (I currently run it at https://stemmaweb.net/stemmaweb with a Wordpress instance on the root site. So the static bundle would be under `/stemmaweb` and the middleware under another endpoint (e.g. `/stemmaweb/request`). As discussed in the call, I think these should both go into the same container; I have a hard time seeing a use case for splitting the middleware into its own container.
> 
> > Also, is there a live instance of the Stemmarest API deployed somewhere?
> 
> Yes, it is running behind https://test.stemmaweb.net/stemmaweb . I'll give you the access details separately.

With the current dockerized setup, the frontend is accessible at [http://localhost:8888/stemmaweb/](http://localhost:8888/stemmaweb/) and the middleware at [http://localhost:8888/stemmaweb/requests/](http://localhost:8888/stemmaweb/requests/).

However, environment variable files need to be placed at various places for this (l will share these through a non-public channel).

Since the reverse-proxied setup needed various modifications in the code (to use relative paths to assets for example) I think it would make sense to setup a dev environment that is structurally identical to the to-be-deployment. Under structural identity all I mean is that we work with the frontend at `<scheme>:<host>:<port>/stemmaweb/` and the middleware at `<scheme>:<host>:<port>/stemmaweb/requests/` already at development time. This way, we could avoid running into hard-to-debug scenarios where something works locally in dev, but it fails in prod. I would prefer to fail fast while in dev mode.

I would open a separate issue for a dockerized dev env setup. It would be beneficial also because newcomers to the project should be able to jump into the development after setting a few env vars and executing some `docker-compose up  ...` command. @tla, @jorisvanzundert, what do you think?

**Comment by tla** [comment]
> Since the reverse-proxied setup needed various modifications in the code (to use relative paths to assets for example) I think it would make sense to setup a dev environment that is structurally identical to the to-be-deployment. Under structural identity all I mean is that we work with the frontend at `<scheme>:<host>:<port>/stemmaweb/` and the middleware at `<scheme>:<host>:<port>/stemmaweb/requests/` already at development time. This way, we could avoid running into hard-to-debug scenarios where something works locally in dev, but it fails in prod. I would prefer to fail fast while in dev mode.
> 
> I would open a separate issue for a dockerized dev env setup. It would be beneficial also because newcomers to the project should be able to jump into the development after setting a few env vars and executing some `docker-compose up ...` command. @tla, @jorisvanzundert, what do you think?

Yes, that is fine; go for it. Does this mean you're ready for me to merge this pull request?

**Comment by peter-gy** [comment]
@tla, yes please, this PR is ready. I would work on the dev-env setup in a separate issue.

**Pull request merged**
